"""create_counties

Revision ID: c5f1202c4d56
Revises: fea192ad9f0f
Create Date: 2026-05-21 16:05:26.244466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f1202c4d56'
down_revision: Union[str, Sequence[str], None] = 'fea192ad9f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counties_id'), 'counties', ['id'], unique=False)
    op.create_index(op.f('ix_counties_name'), 'counties', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counties_name'), table_name='counties')
    op.drop_index(op.f('ix_counties_id'), table_name='counties')
    op.drop_table('counties')
    # ### end Alembic commands ###
